# Generated by Django 5.1.3 on 2024-11-14 08:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_id', models.IntegerField(max_length=100)),
                ('input_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('input_currency', models.CharField(max_length=3)),
                ('output_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('output_currency', models.CharField(max_length=3)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
