# Generated by Django 5.1.3 on 2024-11-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='input_amount',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='output_amount',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
