# Generated by Django 5.1.3 on 2024-11-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
